baseurl      = "https://www.edwinwalela.com"
title        = "Edwin walela"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "I'm a Web Developer"

  twitter = 'http'

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "A journey through code"
  keywords = "webdevelopment, blog, webdeveloper,"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Edwin Walela"
    subtitle = "Web Developer"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /edwin/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[params.social]]
    name = "github"
    url  = "https://github.com/edwinwalela"
    
  [[params.social]]
    name = "medium"
    url  = "https://medium.com/@edwinwalela"

  [[params.social]]
    name = "email"
    url  = "mailto:edwinwalela@gmail.com"

